version: '3.8'
services:
  lunarvim:
    build:
      context: .
      dockerfile: lunarvim.dockerfile
      ssh:
        - default
    image: lunarvim:v0
    container_name: lunarvim_install
    volumes:
      - .:/workspace
      # - $SSH_AUTH_SOCK:/tmp/ssh_auth_sock
      - $HOME/.ssh/id_github:/workspace/id_github
      - $HOME/.ssh/id_github.pub:/workspace/id_github.pub
    environment:
      - TZ=Asia/Shanghai
      # - SSH_AUTH_SOCK=/tmp/ssh_auth_sock